# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple, Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

<<<<<<< HEAD
__version__ = version = '0.1.dev4+gd41ddbb.d20241206'
__version_tuple__ = version_tuple = (0, 1, 'dev4', 'gd41ddbb.d20241206')
=======
__version__ = version = "0.1.dev4+gd41ddbb.d20241002"
__version_tuple__ = version_tuple = (0, 1, "dev4", "gd41ddbb.d20241002")
>>>>>>> 5e79b42fa4b02d5ff9be9eb6b38bc144db664a6f
